service: aws-nodejs # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
custom:
  account: ${opt:account}
  cloudfront-app:
    region: us-east-1
    bucketName: ${opt:bucket}
    useragentsecret: ${opt:uasecret}
    acm-region: us-east-1
    certid: ${opt:certid}
    logbucket: ${opt:logbucket}
    prefix: "${self:provider.stage}-${self:service}"
resources:
  Resources:
    WebAppS3Bucket: ${file(cloudfront-app.yml):WebAppS3Bucket}
    WebAppS3BucketPolicy: ${file(cloudfront-app.yml):WebAppS3BucketPolicy}
    WebAppDistribution: ${file(cloudfront-app.yml):WebAppDistribution}